spring:
  datasource:
    url: jdbc:h2:mem:flowchartDb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass123
  h2:
    console:
      enabled: 'true'
  application:
    name: FlowchartManagementSystem
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
